@endpoint = /groups



### GET ALL RESOURCE

GET {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}



### GET RESOURCE WITH FILTERS AND PAGINATION

GET {{hostname}}{{endpoint}}?page=1&limit=2
content-type: application/json
Authorization: {{token}}



### GET SINGLE RESOURCE

GET {{hostname}}{{endpoint}}/6401f24b3c3d5cb4e6303ff0
content-type: application/json
Authorization: {{token}}



### ADD/STORE RESOURCE

POST {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}

{
    "name": "Phantom Troupe",
    "also_known_as": ["Gen'ei Ryodan", "Spiders"],
    "status": "active",
    "leaders": ["64d6ffcd51403af1e30e7663"],
    "classification": "thieves"
}



### UPDATE RESOURCE

PATCH {{hostname}}{{endpoint}}/6401f24b3c3d5cb4e6303ff0
content-type: application/json
Authorization: {{token}}

{
    "mobileNumber": "09233",
    "email": "email@gmail3.com",
    "lastName": "Mil",
    "firstName": "Ez"
}



### DELETE RESOURCE

DELETE {{hostname}}{{endpoint}}/6401f24b3c3d5cb4e6303ff0
content-type: application/json
Authorization: {{token}}