@endpoint = /guest

### GET SELF (as admin)
GET {{hostname}}{{endpoint}}/self
Authorization: {{token}}

### GET SELF (as guest via api_key)
GET {{hostname}}{{endpoint}}/self{{api_key}}

### REGISTER USER
POST {{hostname}}{{endpoint}}/register
content-type: application/json

{
	"email": "akocero15@gmail.com",
	"name": "erro doe",
	"usage": "educational purpose only"
}

### GET SELF
GET {{hostname}}{{endpoint}}/self_verify?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTE4MTcwOTcsImV4cCI6MTY5NDQwOTA5N30.65CuDXZxpm8VqgqzyZam9WIFUvF_Rfnfk3Onv7TSuc8