@endpoint = /images

GET {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}
###

GET {{hostname}}{{endpoint}}/6411c4dbf8e48cb5b3b1546f
content-type: application/json
Authorization: {{token}}

###
POST {{hostname}}{{endpoint}}
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{token}}

--boundary
Content-Disposition: form-data; name="file"; filename="b0jnxdp6axmbpd0fxzti.webp"
Content-Type: image/webp

< ../../../hxh_images/b0jnxdp6axmbpd0fxzti.webp
--boundary--

###
PATCH {{hostname}}{{endpoint}}/6401f24b3c3d5cb4e6303ff0
content-type: application/json
Authorization: {{token}}

{
    "mobileNumber": "09233",
    "email": "email@gmail3.com",
    "lastName": "Mil",
    "firstName": "Ez"
}

###
DELETE {{hostname}}{{endpoint}}/6401f24b3c3d5cb4e6303ff0
content-type: application/json
Authorization: {{token}}