#@hostname = http://localhost:4000/api/v1
@hostname = https://hxh-api.cyclic.cloud/api/v1
@endpoint = /characters
@api_key = ?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTA3NTRlNGJmZjA0NzExYzQxYjg0YSIsImlhdCI6MTY5MjQzMTY5NSwiZXhwIjoxNjk1MDIzNjk1fQ.oPElF-WwJuk378oeM2fv4lJrweX-iKl3_d2u06bFvVA
### GET ALL RESOURCE
GET {{hostname}}{{endpoint}}{{api_key}}
content-type: application/json

### GET ONE RANDOM
GET {{hostname}}{{endpoint}}/random{{api_key}}
content-type: application/json

### GET RESOURCE WITH FILTERS AND PAGINATION
GET {{hostname}}{{endpoint}}{{api_key}}&page=1&limit=2
content-type: application/json

### GET SINGLE RESOURCE
GET {{hostname}}{{endpoint}}/64d88ffbcbad61354d10e60a{{api_key}}
content-type: application/json

