@endpoint = /groups

### GET ALL RESOURCE
GET {{hostname}}{{endpoint}}
content-type: application/json
X-API-Key: {{api_key}}

### GET ONE RANDOM
GET {{hostname}}{{endpoint}}/random
content-type: application/json
X-API-Key: {{api_key}}

### GET RESOURCE WITH FILTERS AND PAGINATION
GET {{hostname}}{{endpoint}}?page=1&limit=2
content-type: application/json
X-API-Key: {{api_key}}

### GET SINGLE RESOURCE
GET {{hostname}}{{endpoint}}/64d6ffcd51403af1e30e7663
content-type: application/json
X-API-Key: {{api_key}}
